### PR TITLE
Check for alloc_size attribute in configure.ac

### LINKED ISSUE #668: `alloc_size` requires GCC 4.3
As referenced in #667, you get a warning about an unknown attribute `alloc_size` when compiling `Compat.c`, because the function attributes for the allocators are only defined for GCC 4.3 and above:
https://github.com/htop-dev/htop/blob/07170aee4cb3bbe0efadd6c60c50d421583a9b6d/Macros.h#L40-L41

### PR DESCRIPTION
**Pull request by BenBE**
Fixes #668

### CODE REVIEW

**Comment by BenBE** [comment]
@polluks Can you please have a look if those warnings you saw in #667 (besides the undefined symbols errors) when compiling `Compat.c` are still present or if they are fixed by this patch?

**Comment by polluks** [comment]
@BenBE Still the same. I suppose you have to check the compiler version.

**Comment by BenBE** [comment]
Can you provide the `config.log`? Really wondering why the `configure` isn't picking up that warning (there's a compiler check in configure that should catch this case).

**Comment by polluks** [comment]
Oops, I have to do first a `git pull origin pull/670/head`.

**Pull request merged**
