### PR TITLE
Color scheme for red/green colorblind

### PR DESCRIPTION
**Pull request by rrobgill**
As discussed in #905 some color contrasts used in the included color schemes are difficult to distinguish by colorblind people.

This additional color scheme avoids using red/green contrast, substituting yellow/blue where possible, and using brightness variation to further increase contrast. 

Signed-off-by: Rob Gill <rrobgill@protonmail.com>

### CODE REVIEW

**Comment by Explorer09** [comment]
I don't know if it helps when I post an example screenshot:
Screenshot

I'm not sure I like it, but applying the color scheme seems to reveal problems (that applies even to default color scheme as well):
1. We didn't mark kernel threads with distinct color from user process threads.
2. The default color scheme tend to avoid dark blue color for displaying text (as it is hard to read) and replace them with light/bold blue (this color is different from cyan) through special exceptions in color definitions (e.g. `MEMORY_BUFFERS_TEXT` vs. `MEMORY_BUFFERS`). These special exceptions should be removed as we expand the possible color schemes (in a separate PR). Otherwise you can see in the screenshot, kernel CPU time (`sy:`) and cache in Swap (`Swp cache:`) look too dark.

**Comment by rrobgill** [comment]
Light blue and Cyan are

**Comment by rrobgill** [comment]
I may return after the expanded colorschemes PR

**Comment by BenBE** [comment]
If we are going the route of catering for colorblind people we should not only take the common red/green variant into account, but the somewhat rarer yellow/blue variant too. Otherwise we're kinda back on square one.

**Pull request closed without merging**
