### PR TITLE
Revert color change on LightTerminal

### PR DESCRIPTION
**Pull request by cgzones**
Partially revert 4b14ab9789eee004daab8594ac00a113c18af060

`ColorPair(Black,Black)` is not actually black on black, but due to
adjustments in `CRT_setColors()` black on default-background-color.

Thanks to V for reporting.

/cc @deviant

### CODE REVIEW

**Comment by deviant** [comment]
Hi! I'm definitely in favour of seeing this merged, and have some additional changes to contribute. I'd made the same patch, and was working on further improving the consistency/readability of the theme. How would you like to go about combining these?

**Comment by BenBE** [comment]
> How would you like to go about combining these?

Just make a PR for your changes and possibly reference this PR. If the changes are small enough (preferably only fixes right now) this can go along with this one. If in doubt split your commits to separate minor tweaks and other changes and we'll cherry-pick the small issues accordingly.

**Comment by deviant** [comment]
@BenBE Just a few colour redefinitions. I also found a bug in the palette logic, but I guess that part can go in another PR.

**Comment by BenBE** [comment]
> @BenBE Just a few colour redefinitions.

Those should be mostly fine. Also cf. #190 which recently got merged.

> I also found a bug in the palette logic, but I guess that part can go in another PR.

Looking forward to more details on that one.

**Pull request merged**
