### PR TITLE
Add Linux process column for total context switches

### PR DESCRIPTION
**Pull request by cgzones**
Displays the incremental sum of voluntary_ctxt_switches and nonvoluntary_ctxt_switches.

Closes: #113

### CODE REVIEW

**Comment by xkill** [comment]
The problem with this patch is that it shows the accumulated context switches. It should show the difference between the actual status and the previous refresh.

**Comment by cgzones** [comment]
Added commit to show the difference instead of accumulated total

**Comment by xkill** [comment]
Great, works fine!!!

**Comment by cgzones** [comment]
Should values above a certain value (>1000 ?) be highlighted (bold ?) ?

**Comment by cgzones** [comment]
Should values above a certain value (>1000 ?) be highlighted (bold ?) ?

**Comment by BenBE** [comment]
I think usual big number highlighting (starting blue for thousands, red for millions) would be fine …

**Comment by cgzones** [comment]
Entries above 1000 are now display in bold.

**Pull request merged**
