### PR TITLE
Add some base compiler warnings

### PR DESCRIPTION
**Pull request by cgzones**
Includes #102

### CODE REVIEW

**Comment by BenBE** [comment]
For the unused arguments patch I'd suggest having a globally available macro `HTOP_UNUSED` that is used inside the function body. Using the `__attribute__((unused))` is mostly GCC syntax (and incidentally also supported on LLVM for GCC compat).

```c
// In some global header:
#define HTOP_UNUSED(v) (void)(v)

//Inside functions with unused arguments:
void example_foo(int unused_var) {
    HTOP_UNUSED(unused_var);

    // Rest of the function code.
}
```

Using that macro definition is portable even outside GCC/LLVM.

**Comment by BenBE** [comment]
I'm not quite happy with the naming of those macros, as names with leading underscores are normally reserved for the compiler/standard library to use. Any particular reason for doing the current naming?

**Comment by fasterit** [comment]
Could you separate out the fixes (e.g.2b98e3f) from the new precompiler macros? 
We just discussed this PR in the core team meeting (you had an invite but did not respond). May be you can join next week, I'll send you another invite email.

**Comment by cgzones** [comment]
Separated hwlock-linux_affinity commit into #107

**Pull request merged**
