### PR TITLE
Use getpwuid_r to avoid static OS buffers

### PR DESCRIPTION
**Pull request by BenBE**

### CODE REVIEW

**Comment by natoscott** [comment]
Hmm ... but why?  AFAICS there's no reason to do this (htop is not threaded, using static buffers is fine) and adding malloc/free of a local 16KB buffer just slows things down and adds more code.

**Comment by BenBE** [comment]
This patch is mostly written to check the MacOS memleak issue.

We can make the 16K buffer static too. Intention was mostly to avoid any dynamic allocations in system libraries.

You can mark this WIP for now if you like.

**Comment by cgzones** [comment]
I don't like this neither: `getpwuid()` is a totally usable function in a single-threaded program.
We should not complicate code, due to the Darwin's libc implementation not cleaning up a one-time static buffer.

**Comment by cgzones** [comment]
NAK (for now)

**Pull request closed without merging**
