### PR TITLE
adding Increament Decreament labels for Setup Panel

### PR DESCRIPTION
**Pull request by rustedusted**
Referring to the issue #737

### CODE REVIEW

**Comment by rustedusted** [comment]
currently added label and key events as well i didn't see anything more

**Comment by rustedusted** [comment]
if there is anything more please do tell me 

i'm also thinking of adding another button maybe f9 to toggle checkOptions

**Comment by BenBE** [comment]
This change alone doesn't do anything except show some text. There's code missing to actually handle these two keys.

Also on the note re checkboxes: They already react to <kbd>Space</kbd> and <kbd>Enter</kbd> … No need for yet another option …

**Comment by rustedusted** [comment]
oh wait did i not commit the key changes

oh i did not sorry for that

**Comment by rustedusted** [comment]
oh wait did i not commit the key changes

oh i did not sorry for that

**Comment by rustedusted** [comment]
it's just like 3 lines of change tbh is there anything more expected??

please do tell me

**Comment by rustedusted** [comment]
hey there any updates to this?!

**Pull request closed without merging**
