### PR TITLE
Set reasonable total value for Load Meters

### PR DESCRIPTION
**Pull request by cgzones**
Needed for graph and bar mode

### CODE REVIEW

**Comment by fasterit** [comment]
Can you explain the rationale? Why 1.5?

**Comment by cgzones** [comment]
Currently the total value for the LoadMeters is 100.
Thereby in MeterMode Graph there is (almost always) no data printed, cause the Load (in case of the LoadAverageMeter the accumulated 1+5+15 load) is far less than 100.
`1.5 *` is just a guess for a sensible maximum value, do you prefer `1.0 *` or something higher?
(In case the actual load is higher than the guessed maximum, it is still displayed as 100%, since it's getting adjusted with MAXIMUM.)

**Comment by fasterit** [comment]
I would have used 2 (two) as the initial maximum (as it will adjust upwards when real maxima are hit as you said). Load is a measure for the amount of processes & threads waiting in (uninterruptible) sleep (for resources). Hence it is not CPU (core) bound per se. You seem to use the common sense experience that lots of cores have lots to do but that may only be true on servers. I assume most desktop CPUs will be idling with a load around 1-2 typically. So using 2 as a common upper bound seems reasonable to me and on machines with real load it will quickly adjust upwards.

**Comment by BenBE** [comment]
Typically when I look at the load value (numerically) I check if it's above about twice of the CPU count to check if the machine is overloaded. That's also when really compiling a lot of stuff what I usually give for the parallelism as you typically have some proceses waiting for I/O, others waiting for other resources.

So putting the load at 1*CPUcount or 2*CPUcount are two values you could easily compute in your head, being 1*CPUcount being "there's always some work for every core in the system" being a meaningful ground. Having the value statically at e.g. 1 or 2 would already drown the load meter in static noise on my desktop (currently idle at about 0.5); probably getting only worse on systems with many more cores. I think 1 would be a good value if we normalized by CPU count, as than it would roughly represent the amount of time the power of the CPU was used (by any process).

**Comment by Explorer09** [comment]
Load average value is not supposed to have an upper limit. For bar display, it's better to have a limit that's dynamically scaled.
I remember I experimented the feature before. See #129 if you guys are interested to test.

**Comment by cgzones** [comment]
Superseded by revamp of total values in #129

**Pull request closed without merging**
