### PR TITLE
LoadMeter: dynamically adjust color and total of Bar 

### PR DESCRIPTION
**Pull request by cgzones**
Change the color and total based on the actual 1min load value:

    < 1         : green and total of 1.0
    < cpu-count : yellow and total of cpu-count
    else        : read and total of 2*cpu-count

Closes: #32

### CODE REVIEW

**Comment by pthfdr-42** [comment]
This should be used on graph as well.

**Comment by BenBE** [comment]
Just a minor typo fix in the commit message.

**Review by BenBE — APPROVED** [review]
LGTM.

**Comment by eworm-de** [comment]
This is kind of inconsistent IMHO.
Probably depends on the type of machine (desktop/notebook vs. server), but for green I would use `< cpu-count/2`.

**Comment by BenBE** [comment]
IMHO this is fine this way, as `cpu-count` is always `>1` which isn't guaranteed for `cpu-count/2`.

Semantically the current limits mean, that for green there will always be some time where the whole CPU could be sleeping/idling. With yellow, there is potentially always one task for execution (thus likely no CPU idle time) and with read you're likely to start experiencing symptoms of a busy system.

**Pull request merged**
