### PR TITLE
CI: Bump NetBSD version to 10.0.

### PR DESCRIPTION
**Pull request by fraggerfox**
Bump NetBSD to version `10.0` in the CI.

### CODE REVIEW

**Comment by Explorer09** [comment]
@fraggerfox  With #1453, there would be no more build errors with NetBSD 10.0. Is there anything else you wish to fix before you bump the NetBSD version?

**Comment by fraggerfox** [comment]
> @fraggerfox With #1453, there would be no more build errors with NetBSD 10.0. Is there anything else you wish to fix before you bump the NetBSD version?

oh nice! Thank you for investigating and fixing it in #1453 , I guess I can close this PR in favor of you doing a bump of NetBSD to `10.0` in yours.

**Comment by Explorer09** [comment]
@fraggerfox Would you please add the "CI" keyword in the commit message? This could reduce confusion when I read the commit history (we're not bumping the OS version requirements, but only OS to test in the CI).

**Comment by BenBE** [comment]
@fraggerfox / @Explorer09: Took the liberty to update the commit message accordingly …

**Review by BenBE — APPROVED** [review]

**Pull request merged**
